@startuml
class w08_threads_runnables_executors {
    -customer: String
    -type: String
    -size: int
    -cookTime: long

    +w08_threads_runnables_executors(customer: String, type: String, size: int, cookTime: long)
    +run() String
}
@enduml

@startuml
class w08_threads_runnables_executors_execute {
    main(String[] args)
}
@enduml

@startuml
w08_threads_runnables_executors_execute -> w08_threads_runnables_executors: Send 4 threads using myService.execute()
w08_threads_runnables_executors_execute <-- w08_threads_runnables_executors: Send start string
w08_threads_runnables_executors_execute <-- w08_threads_runnables_executors: Send cooking string
w08_threads_runnables_executors -> w08_threads_runnables_executors: Sleep for 1 minute
w08_threads_runnables_executors_execute <- w08_threads_runnables_executors: Send end cooking string
@enduml